#!/bin/bash

# Note: This script should be used under the root directory of the project.

if ! cd src/main/resources; then
  echo "Error: Please run this script under the root directory of the project." >&2
  exit 1
fi
make
cd ../../..

./gradlew build

if [ ! -d bin ]; then
    mkdir bin
fi

tar -xvf build/distributions/Mx-Compiler-1.0-SNAPSHOT.tar -C bin/
cd bin/
mv Mx-Compiler-1.0-SNAPSHOT/ mxc/
