#!/bin/bash

# Note: This script should be used under the root directory of the project.

set -e

make -C src/main/resources
./gradlew build

mkdir -p bin/
mkdir -p tmp/

tar -xvf build/distributions/Mx-Compiler-1.0-SNAPSHOT.tar -C tmp/
rm -rf bin/*
mv tmp/Mx-Compiler-1.0-SNAPSHOT/* bin/
